# Generated by Django 3.0.5 on 2020-05-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pessoas', models.IntegerField()),
                ('ids_pessoas', models.CharField(max_length=200)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
    ]
